name: opera_app
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.3
  - boto3
  - gdal=3.2.2
  - geopandas=0.10.2
  - geoviews=1.9.5
  - geoviews-core=1.9.5
  - holoviews=1.14.9
  - hvplot=0.8.0
  - ipykernel=6.15.0
  - ipython
  - matplotlib
  - nodejs=14.18.3
  - notebook=6.4.12
  - numba=0.55.1
  - numpy=1.21.6
  - panel=0.13.1
  - pip
  - python=3.7
  - requests
  - rasterio=1.2.6
  - rioxarray
  - xarray=0.20.2
  - pip:
    - folium
    - gdal-utils
    - jupyterlab==3.4.3
    - jupyterlab-server==2.14.0
    - lxml
    - pystac-client
    - scikit-image
    - selenium